DROP TABLE ORDER IF EXITS;
DROP TABLE NORMAL IF EXITS;
DROP TABLE DIAGNOSTIC IF EXITS;
DROP TABLE TUBE IF EXITS;
DROP TABLE CATEGORY IF EXITS;
DROP TABLE PATIENT IF EXITS;
DROP TABLE PHYSICIAN IF EXITS;


CREATE TABLE PHYSICIAN 
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 221000001),
	NAME 		VARCHAR(255) not null,
	SPCIALTY	VARCHAR(255) null,
	Note		VARCHAR(255) NULL,
);


CREATE TABLE PATIENT 
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 22022000001),
	NAME 		VARCHAR(255) not null,
	AGE			INT not null,
	GENDER		TINYINT not null,
	REFERRAL	BIGINT NULL,
);

CREATE TABLE CATEGORY 
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 101),
	NAME 		VARCHAR(255) not null,
);

CREATE TABLE TUBE 
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 201),
	NAME 		VARCHAR(255) not null,
	IMAGE		VARCHAR(255) not null
);

CREATE TABLE DIAGNOSTIC 
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 501),
	NAME 		VARCHAR(255) not null,
	CATEGORYID	BIGINT not null REFERENCES CATEGORY(ID),
	REQUISITE	VARCHAR(255) null,
	TUBEID		BIGINT not null,
);

CREATE TABLE NORMAL
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 1001),
	TESTID 		VARCHAR(255) not null REFERENCES DIAGNOSTIC(ID),
	AGE			INT not null,
	GENDER		TINYINT not null,
	REFERRAL	BIGINT NULL,
);

CREATE TABLE DISCOUNT
(
    ID  			BIGINT not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 500),
    DISCOUNTVALUE 	DECIMAL,
    STARTDATE     	TIMESTAMP,
    ENDDATE       	TIMESTAMP,
    PUBLISH 		VARCHAR(255),
    description  	VARCHAR(255),
    discountCode  	VARCHAR(255)

);


CREATE TABLE ORDER 
(
	ID 			BIGINT  not null primary key GENERATED ALWAYS AS IDENTITY (START WITH 5202200001),
	PATIENT		BIGINT not null REFERENCES PATIENT(ID),
	CREATED		TIMESTAMP not null,
	UPDATED		TIMESTAMP not null,
	TOTAL		DOUBLE NULL,
	DISCOUNT	DOUBLE NULL,
	STATUS		TINYINT not null,
	DISCOUNTID	BIGINT Null
);



